name: WebAPI Dev

on:
  workflow_dispatch:

  push:
    branches:
      - dev
    paths:
      - "src/api/**"
      - "src/Directory.Packages.props"

  pull_request:
    branches:
      - dev
    paths:
      - "src/api/**"
      - "src/Directory.Packages.props"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: restore dependencies
        run: dotnet restore ./src/api/server/Server.csproj
      - name: build
        run: dotnet build ./src/api/server/Server.csproj --no-restore
      - name: test
        run: dotnet test ./src/api/server/Server.csproj --no-build --verbosity normal

  publish:
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish to github container registry
        working-directory: ./src/api/server/
        run: |
          dotnet publish -c Release -p:ContainerRepository=ghcr.io/solanaspindev/webapi -p:ContainerImageTags=latest -p:RuntimeIdentifier=linux-x64
          docker push ghcr.io/solanaspindev/webapi --all-tags
          
  recreate:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: find container and recreate it
        env:
          PORTAINER_API_TOKEN: ${{ secrets.PORTAINER_API_TOKEN }}
          PORTAINER_API_URL: ${{ vars.PORTAINER_API_URL }}
        run: |
          response=$(curl -s -H "X-API-Key: $PORTAINER_API_TOKEN" "$PORTAINER_API_URL/endpoints/2/docker/containers/json")
          id=$(echo $response | jq -r '.[] | select(.Image == "ghcr.io/solanaspindev/webapi:latest") | .Id')
          echo "recreating container with id $id"
          curl -X POST -s \
          -H "X-API-Key: $PORTAINER_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"PullImage":true}' \
          "$PORTAINER_API_URL/docker/2/containers/$id/recreate"
